server:
  port: 5001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:com/xiao/dao/mapper/*.xml
  type-aliases-package: com.xiao.entity